version: '3'
services:
  poc-bank-ft-db:
    image: postgres:9.6.1
    container_name: poc-bank-ft-db-postgres-01
    volumes:
      - ./config/db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    expose:
      - "5432"

  poc-bank-ft-web:
    build: .
    container_name: poc-bank-ft-web-django-01
    command: bash -c "cd ./poc_bank && gunicorn -b 0.0.0.0:8000 poc_bank.wsgi:application"
    depends_on:
      - poc-bank-ft-db
    volumes:
      - ./poc_bank:/bank_demo/poc_bank
    ports:
      - "8000:8000"
    expose:
      - "8000"

  poc-bank-ft-static:
    image: nginx:1.10.3
    container_name: poc-bank-ft-static-nginx-01
    depends_on:
      - poc-bank-ft-web
    volumes:
      - ./poc_bank:/bank_demo/poc_bank
      - ./config/nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
