# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 18:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.CharField(max_length=15)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=35)),
                ('account_type', models.CharField(choices=[('s', 'Savings'), ('c', 'Current')], default='s', max_length=1)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fund_transfer.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='FundTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('narration', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('customer_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fund_transfer.CustomerAccount')),
            ],
        ),
        migrations.CreateModel(
            name='Payee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('nickname', models.CharField(max_length=30)),
                ('account_number', models.CharField(max_length=35)),
                ('account_type', models.CharField(choices=[('s', 'Savings'), ('c', 'Current')], default='s', help_text='Please choose the account / card type', max_length=1, verbose_name='Account / Card type')),
                ('bank_code', models.CharField(max_length=50)),
                ('bank_name', models.CharField(max_length=50)),
                ('bank_city', models.CharField(max_length=50)),
                ('bank_branch', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fund_transfer.Customer')),
            ],
        ),
        migrations.AddField(
            model_name='fundtransfer',
            name='payee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fund_transfer.Payee'),
        ),
    ]
